import financial from "../images/usecase-icons/financial.png"
import ad from "../images/usecase-icons/ad.png"
import mfg from "../images/usecase-icons/mfg.png"
import business from "../images/usecase-icons/business.png"
import medical from "../images/usecase-icons/medical.png"
import travel from "../images/usecase-icons/travel.png"

export default [
  {
    id: 1,
    name: "A",
    icon: financial,
    left: 220,
    top: 250,
    size: 42,
    x: 10,
    color: "#FFEE58",
    url: "url(#A)",
    title: "Financial Services",
    description: "We provide financial market speculation, fraud & AML detection, and faster transaction & application fullfilment (loans, insurance, etc.)",
  },
  {
    id: 2,
    name: "B",
    icon: ad,
    left: 320,
    top: 40,
    size: 40,
    x: 20,
    color: "#D32F2F",
    url: "url(#B)",
    title: "Ad Tech",
    description: "For advertising, we're eminent in customer profiling, data management & governance, and focused-marketing strategies.",
  },
  {
    id: 3,
    name: "C",
    icon: mfg,
    left: 500,
    top: 10,
    size: 40,
    x: 30,
    color: "#FFCC80",
    url: "url(#C)",
    title: "Supply Chain / Manufacturing",
    description: "Our business covers Planning & Optimization, and Resource Optimization, which satisfies Fault-tolerance & Maitenance, etc. ",
  },
  {
    id: 4,
    name: "D",
    icon: business,
    left: 820,
    top: 200,
    size: 40,
    x: 40,
    color: "#F48FB1",
    url: "url(#D)",
    title: "Business",
    description: "What you can get for your own business are, safe and efficient Global Trade, Business Health, Tax & Cash Flow Optimization, and Employee & Customer Profiling.",
  },
  {
    id: 5,
    name: "E",
    icon: medical,
    left: 790,
    top: 310,
    size: 40,
    x: 50,
    color: "#AED581",
    url: "url(#E)",
    title: "Medical",
    description: "Our services are Omni-present Medical Records & Accountability, Data Governance & Analysis and Predictive Analysis, etc., for medical industries.",
  },
  {
    id: 6,
    name: "F",
    icon: travel,
    left: 460,
    top: 450,
    size: 40,
    x: 60,
    color: "#00ACC1",
    url: "url(#F)",
    title: "Travel",
    description: "For travel angencies and companies, we provide Identity Management, International Wallet Access and Localized Customer Services, etc.",
  },
]